apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
      - name: sa-frontend
        image: wendycc28/sa-frontend:v1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

      volumes:
      - name: nginx-conf
        configMap:
          name: sa-frontend-nginx
          items:
          - key: nginx.conf
            path: nginx.conf
