apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  namespace: default
  labels:
    app: sa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
        - name: sa-frontend
          image: wendycc28/sa-frontend:v1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: sa-frontend-nginx
            items:
              - key: nginx.conf
                path: nginx.conf
