apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-frontend-nginx
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
      upstream webapp {
        server sa-webapp.default.svc.cluster.local:8080;
      }

      server {
        listen 80;

        
        location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri /index.html;
        }

        
        location /api/ {
          proxy_pass http://sa-web-app-lb:8080;
        }
      }
    }

